# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('trabalho', models.CharField(max_length=500)),
                ('trabalhoKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Trabalho')),
            ],
        ),
    ]
