# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_submissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='professor',
        ),
    ]
