# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_remove_trabalho_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='descricao',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
