# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0004_auto_20161106_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='status',
            field=models.CharField(default='Não enviado', max_length=30),
        ),
    ]
