# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0006_auto_20161106_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabalho',
            old_name='turma',
            new_name='professor',
        ),
    ]
