# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0007_auto_20161106_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
