# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_trabalho_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
