# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0009_auto_20161109_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='keyCode',
            field=models.CharField(default='', max_length=8),
        ),
    ]
