# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0010_submissao_keycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissao',
            name='keyCode',
        ),
        migrations.AddField(
            model_name='submissao',
            name='passwordsend',
            field=models.BooleanField(default=False),
        ),
    ]
