# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0015_auto_20161128_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissao',
            name='trabalhoKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Trabalho'),
        ),
    ]
