# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0016_auto_20161128_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissao',
            name='aluno',
        ),
        migrations.AlterField(
            model_name='submissao',
            name='trabalhoKey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Portal.Trabalho'),
        ),
    ]
