# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20161025_0340'),
        ('Portal', '0017_auto_20161128_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissao',
            name='id',
        ),
        migrations.AddField(
            model_name='submissao',
            name='aluno',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissao',
            name='trabalhoKey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portal.Trabalho'),
        ),
    ]
