# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0019_auto_20161207_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
