# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0020_auto_20161207_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='removido',
            field=models.BooleanField(default=False),
        ),
    ]
