# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0021_trabalho_removido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissao',
            name='correctPassword',
        ),
        migrations.AddField(
            model_name='submissao',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
