# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0023_submissao_filr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissao',
            old_name='filr',
            new_name='file',
        ),
    ]
