# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0026_auto_20161209_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabalho',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissao',
            name='trabalhoKey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Portal.Trabalho'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='turma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Turma'),
        ),
    ]
