# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0027_auto_20161209_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Turma'),
        ),
    ]
