# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0028_auto_20161213_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='trabalhoKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Trabalho'),
        ),
    ]
