# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0029_auto_20161213_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuario'),
        ),
    ]
