# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:02
from __future__ import unicode_literals

import Portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0030_auto_20161213_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Portal.models.path_diretorio_professor),
        ),
    ]
