# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0031_auto_20161214_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='aluno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='professor',
            field=models.IntegerField(),
        ),
    ]
