# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 16:48
from __future__ import unicode_literals

import Portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0032_auto_20161214_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='nomealuno',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissao',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Portal.models.path_diretorio_aluno),
        ),
    ]
