# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0033_auto_20161215_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='nomeProfessor',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
