# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0034_trabalho_nomeprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='login',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
