# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20161023_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='grau',
            field=models.CharField(max_length=30),
        ),
    ]
