# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20161209_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='Estudantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
