# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_auto_20161214_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
    ]
